dist: trusty

language: android

jdk:
    - openjdk8

android:
    components:
        - tools
        - platform-tools
        - android-27
        - build-tools-27.0.3
        - extra-google-m2repository
        - extra-android-m2repository

before_install:
    - yes | sdkmanager "platforms;android-27" 

before_script:
  - gpg2 --batch --decrypt --passphrase=${GPG_PASSPHRASE} --output boilerplate.jks boilerplate.jks.gpg
  - gpg2 --batch --decrypt --passphrase=${GPG_PASSPHRASE} --output keystore.properties keystore.properties.gpg
  - gpg2 --batch --decrypt --passphrase=${GPG_PASSPHRASE} --output google-play-publisher.json google-play-publisher.json.gpg

script: ./build.sh
after_success: ./publish.sh

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
