build:
  maxIssues: 0
  weights:
    complexity: 0
    # style: 1
    # comments: 1
    # LongParameterList: 1

style:
  MagicNumber:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true

