version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-29

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run: 
          name: Decrypt keys
          command: ci/decrypt.sh
      - run:
          name: Build artifacts
          command: ci/build.sh
      - run:
          name: Publish APK
          command: ci/publish.sh
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android/build-cache
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
